"""init 17 tables

Revision ID: 1c1a51600ffc
Revises: 
Create Date: 2026-08-24 17:04:48.994390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '1c1a51600ffc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_source',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='名称'),
    sa.Column('collection_method', sa.Enum('手动录入', 'CSV 导入', '自动采集', name='ds_collection_method'), nullable=False, comment='手动录入/CSV 导入；自动采集枚举仅作架构预留（D5）'),
    sa.Column('business_object', sa.Enum('自己账号', '对标账号', '行业报告', '相关热点', '评论和私信', name='ds_business_object'), nullable=False, comment='自己账号/对标账号/行业报告/相关热点/评论和私信'),
    sa.Column('platform', sa.Enum('视频号', name='ds_platform'), nullable=True, comment='视频号；非平台文本资料可为空'),
    sa.Column('account_identifier', sa.String(length=200), nullable=True, comment='账号类数据必填'),
    sa.Column('is_benchmark', sa.Boolean(), nullable=False, comment='是否对标账号'),
    sa.Column('config', sa.JSON(), nullable=True, comment='⚠️ 新增建议字段：API/OAuth/调度配置（自动采集架构预留）'),
    sa.Column('status', sa.Enum('启用', '停用', name='ds_status'), nullable=True, comment='⚠️ 新增建议字段：启用/停用'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_class',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='分类名（唯一）'),
    sa.Column('parent_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='父级分类，可选层级'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='⚠️ 新增建议字段：排序'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['parent_id'], ['material_class.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('username', sa.String(length=100), nullable=False, comment='唯一登录账号（D7）'),
    sa.Column('password_hash', sa.String(length=200), nullable=False, comment='密码哈希，不保存明文（D7）'),
    sa.Column('role', sa.Enum('管理员', '成员', name='user_role'), nullable=False, comment='管理员/成员'),
    sa.Column('status', sa.Enum('启用', '停用', name='user_status'), nullable=False, comment='启用/停用'),
    sa.Column('functional_permissions', sa.JSON(), nullable=False, comment='管理员分配的功能权限集合'),
    sa.Column('data_scope', sa.JSON(), nullable=False, comment='数据权限范围（全量/指定资料分类/指定数据源）'),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='创建人（种子管理员为空）'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='⚠️ 新增建议字段：最后登录时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('analysis_task',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=100), nullable=True, comment='⚠️ 新增建议字段：任务名称'),
    sa.Column('type', sa.Enum('资料分析', '数据分析', name='analysis_task_type'), nullable=False, comment='指定分析任务类型'),
    sa.Column('prompt_version_snapshot', sa.JSON(), nullable=True, comment='可选提示词版本快照'),
    sa.Column('material_context_snapshot', sa.JSON(), nullable=True, comment='可选资料库上下文快照'),
    sa.Column('output_schema', sa.JSON(), nullable=False, comment='输出字段定义'),
    sa.Column('ai_raw_response', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True, comment='AI 原始响应留档（执行后写入，含失败响应）'),
    sa.Column('status', sa.Enum('待执行', '执行中', '已完成', '失败', '待审核', '已确认', '已废弃', name='analysis_task_status'), nullable=False, comment='待执行/执行中/已完成/失败/待审核/已确认/已废弃'),
    sa.Column('error_message', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True, comment='失败原因留痕（S03）'),
    sa.Column('reviewer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='审核人'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='创建人'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('retry_count', sa.Integer(), nullable=True, comment='⚠️ 新增建议字段：重试次数'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_task', schema=None) as batch_op:
        batch_op.create_index('idx_analysis_task_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_analysis_task_status', ['status'], unique=False)

    op.create_table('prompt_template',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('task_type', sa.Enum('选题生成', '脚本生成', '资料分析', '数据分析', name='prompt_task_type'), nullable=False, comment='选题生成/脚本生成/资料分析/数据分析'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称'),
    sa.Column('content', sa.Text(), nullable=False, comment='提示词正文'),
    sa.Column('version', sa.Integer(), nullable=True, comment='⚠️ 新增建议字段：当前版本号'),
    sa.Column('material_combo', sa.JSON(), nullable=True, comment='固定关联资料组合'),
    sa.Column('output_schema', sa.JSON(), nullable=True, comment='输出字段定义；分析任务必填'),
    sa.Column('status', sa.Enum('启用', '停用', name='prompt_status'), nullable=True, comment='⚠️ 新增建议字段：启用/停用'),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='创建人'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_data',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('source_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='数据源 id'),
    sa.Column('collected_at', sa.DateTime(), nullable=False, comment='采集时间'),
    sa.Column('raw_content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True, comment='原始内容（或本地存储路径）'),
    sa.Column('structured', sa.JSON(), nullable=True, comment='结构化字段；一期仅通用基础结构（D6）'),
    sa.Column('window_start', sa.DateTime(), nullable=False, comment='采集时间窗开始'),
    sa.Column('window_end', sa.DateTime(), nullable=False, comment='采集时间窗结束'),
    sa.Column('clean_dedup_record', sa.JSON(), nullable=False, comment='清洗/去重规则或处理记录'),
    sa.ForeignKeyConstraint(['source_id'], ['data_source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_data', schema=None) as batch_op:
        batch_op.create_index('idx_raw_data_source_id', ['source_id'], unique=False)

    op.create_table('tag',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='标签名（唯一）'),
    sa.Column('group_name', sa.String(length=50), nullable=True, comment='可选标签组；一期不强制分组，可为空（D1）'),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='⚠️ 技术映射：创建人'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('topic',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='选题标题'),
    sa.Column('direction', sa.String(length=50), nullable=False, comment='方向/分类'),
    sa.Column('specialty', sa.Enum('市场营销', '企业经营', '自媒体平台流量与规划算法逻辑', '用户需求与痛点', name='topic_specialty'), nullable=False, comment='专业方向'),
    sa.Column('customer_scenario', sa.String(length=200), nullable=False, comment='结合场景'),
    sa.Column('user_perspective', sa.String(length=200), nullable=False, comment='用户视角'),
    sa.Column('business_direction', sa.String(length=100), nullable=False, comment='经营方向'),
    sa.Column('core_angle', sa.String(length=500), nullable=False, comment='核心角度'),
    sa.Column('topic_principle', sa.String(length=200), nullable=False, comment='选题原则'),
    sa.Column('topic_angle', sa.String(length=200), nullable=False, comment='选题角度'),
    sa.Column('status', sa.Enum('待筛选', '已选定', '已生成脚本', '已使用', '已废弃', name='topic_status'), nullable=False, comment='待筛选/已选定/已生成脚本/已使用/已废弃'),
    sa.Column('batch_no', sa.String(length=50), nullable=True, comment='生成批次号'),
    sa.Column('prompt_version_snapshot', sa.JSON(), nullable=True, comment='可选提示词版本追溯；仅 AI 批量生成路径写入'),
    sa.Column('ai_raw_response', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True, comment='AI 批量生成时留档；独立/手动创建可为空'),
    sa.Column('screening_result', sa.Enum('选中', '淘汰', name='topic_screening_result'), nullable=True, comment='选中/淘汰；完成筛选后必填'),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='创建人'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.create_index('idx_topic_batch_no', ['batch_no'], unique=False)
        batch_op.create_index('idx_topic_direction', ['direction'], unique=False)
        batch_op.create_index('idx_topic_status', ['status'], unique=False)

    op.create_table('analysis_result',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('task_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='任务 id'),
    sa.Column('result_content', sa.JSON(), nullable=False, comment='结构化结果（效果好坏/结论/建议）'),
    sa.Column('writeback_material_status', sa.Enum('未回写', '已回写', name='result_writeback_material_status'), nullable=False, comment='未回写/已回写（独立动作）'),
    sa.Column('writeback_topic_status', sa.Enum('未反哺', '已反哺', name='result_writeback_topic_status'), nullable=False, comment='未反哺/已反哺（独立动作）'),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_task_input',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('task_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='分析任务 id'),
    sa.Column('raw_data_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='原始数据 id'),
    sa.ForeignKeyConstraint(['raw_data_id'], ['raw_data.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'raw_data_id', name='uk_analysis_task_input')
    )
    op.create_table('material',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='资料标题'),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False, comment='资料正文'),
    sa.Column('class_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='所属分类'),
    sa.Column('source_type', sa.Enum('公众号', '报告', '社交', '客户', '思考', '对标', name='material_source_type'), nullable=False, comment='公众号/报告/社交/客户/思考/对标'),
    sa.Column('source_url', sa.String(length=500), nullable=True, comment='来源链接'),
    sa.Column('trust_level', sa.Enum('高', '中', '低', name='material_trust_level'), nullable=False, comment='高/中/低'),
    sa.Column('valid_from', sa.Date(), nullable=False, comment='有效期起'),
    sa.Column('valid_until', sa.Date(), nullable=False, comment='有效期止'),
    sa.Column('status', sa.Enum('草稿', '待审核', '已生效', '已停用', '已过期', '已废弃', name='material_status'), nullable=False, comment='草稿/待审核/已生效/已停用/已过期/已废弃'),
    sa.Column('is_ai_product', sa.Boolean(), nullable=False, comment='是否 AI 产物'),
    sa.Column('source_analysis_task_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='AI 回写资料关联的来源分析任务'),
    sa.Column('reviewer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='审核人'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='创建人'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['class_id'], ['material_class.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['source_analysis_task_id'], ['analysis_task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.create_index('idx_material_class_id', ['class_id'], unique=False)
        batch_op.create_index('idx_material_status', ['status'], unique=False)
        batch_op.create_index('idx_material_title', ['title'], unique=False)
        batch_op.create_index('idx_material_valid_until', ['valid_until'], unique=False)

    op.create_table('script',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('topic_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='基于选题创建时必填；独立创建时可为空、可后补关联（R10）'),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False, comment='脚本正文'),
    sa.Column('style', sa.Enum('专业严谨', '轻松口语', '讲故事', name='script_style'), nullable=False, comment='专业严谨/轻松口语/讲故事'),
    sa.Column('content_elements', sa.JSON(), nullable=False, comment='案例/数据/个人观点'),
    sa.Column('current_version', sa.Integer(), nullable=False, comment='当前版本号'),
    sa.Column('status', sa.Enum('草稿', '待审核', '已通过', '已使用', '已废弃', name='script_status'), nullable=False, comment='草稿(派生)/待审核/已通过/已使用(人工标记 D4)/已废弃'),
    sa.Column('reviewer_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='审核人'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='审核时间'),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='创建人'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('modified_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='最后修改人'),
    sa.Column('modified_at', sa.DateTime(), nullable=False, comment='最后修改时间'),
    sa.Column('material_refs', sa.JSON(), nullable=True, comment='可选资料追溯'),
    sa.Column('prompt_version_snapshot', sa.JSON(), nullable=True, comment='可选提示词版本追溯'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['modified_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('script', schema=None) as batch_op:
        batch_op.create_index('idx_script_status', ['status'], unique=False)
        batch_op.create_index('idx_script_topic_id', ['topic_id'], unique=False)

    op.create_table('analysis_result_material',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('result_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='分析结果 id'),
    sa.Column('material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='回写生成的资料 id'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['analysis_result.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_result_topic',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('result_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='分析结果 id'),
    sa.Column('topic_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='反哺生成的选题 id'),
    sa.ForeignKeyConstraint(['result_id'], ['analysis_result.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('material_tag',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='资料 id'),
    sa.Column('tag_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='标签 id'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('material_id', 'tag_id', name='uk_material_tag')
    )
    op.create_table('script_version',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('script_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='脚本 id'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号（每改+1）'),
    sa.Column('content_snapshot', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False, comment='正文快照'),
    sa.Column('changed_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='修改人'),
    sa.Column('changed_at', sa.DateTime(), nullable=False, comment='修改时间'),
    sa.Column('note', sa.String(length=200), nullable=True, comment='⚠️ 新增建议字段：修改备注'),
    sa.ForeignKeyConstraint(['changed_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['script_id'], ['script.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_material',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('topic_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='选题 id'),
    sa.Column('material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='引用资料 id'),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'material_id', name='uk_topic_material')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic_material')
    op.drop_table('script_version')
    op.drop_table('material_tag')
    op.drop_table('analysis_result_topic')
    op.drop_table('analysis_result_material')
    with op.batch_alter_table('script', schema=None) as batch_op:
        batch_op.drop_index('idx_script_topic_id')
        batch_op.drop_index('idx_script_status')

    op.drop_table('script')
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_index('idx_material_valid_until')
        batch_op.drop_index('idx_material_title')
        batch_op.drop_index('idx_material_status')
        batch_op.drop_index('idx_material_class_id')

    op.drop_table('material')
    op.drop_table('analysis_task_input')
    op.drop_table('analysis_result')
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_index('idx_topic_status')
        batch_op.drop_index('idx_topic_direction')
        batch_op.drop_index('idx_topic_batch_no')

    op.drop_table('topic')
    op.drop_table('tag')
    with op.batch_alter_table('raw_data', schema=None) as batch_op:
        batch_op.drop_index('idx_raw_data_source_id')

    op.drop_table('raw_data')
    op.drop_table('prompt_template')
    with op.batch_alter_table('analysis_task', schema=None) as batch_op:
        batch_op.drop_index('idx_analysis_task_status')
        batch_op.drop_index('idx_analysis_task_created_at')

    op.drop_table('analysis_task')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('material_class')
    op.drop_table('data_source')
    # ### end Alembic commands ###
