"""add phase2 collection and research skeleton tables

Revision ID: c7293fe1b190
Revises: a3f8c2d91e4b
Create Date: 2026-08-26 16:00:58.785668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'c7293fe1b190'
down_revision: Union[str, None] = 'a3f8c2d91e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_account',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('platform', sa.String(length=32), nullable=False, comment='平台；TODO(待确认)：最终平台枚举和接口范围'),
    sa.Column('account_identifier', sa.String(length=255), nullable=False, comment='平台账号标识；TODO(待确认)：字段映射'),
    sa.Column('account_name', sa.String(length=255), nullable=True, comment='页面展示名称；TODO(待确认)'),
    sa.Column('profile_url', sa.String(length=1000), nullable=True, comment='账号主页 URL；TODO(待确认)'),
    sa.Column('benchmark_flag', sa.Boolean(), nullable=False, comment='是否对标账号；复用 context/05 语义；TODO(待确认)：字段映射'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='是否允许新任务选择；TODO(待确认)'),
    sa.Column('notes', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True, comment='操盘手备注；TODO(待确认)'),
    sa.Column('created_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='创建人；TODO(待确认)：外键映射'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='修改时间'),
    sa.Column('last_collected_at', sa.DateTime(), nullable=True, comment='最近采集时间；TODO(待确认)'),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('benchmark_account', schema=None) as batch_op:
        batch_op.create_index('idx_benchmark_account_enabled', ['enabled'], unique=False)
        batch_op.create_index('idx_benchmark_account_platform', ['platform'], unique=False)

    op.create_table('collection_task',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('task_no', sa.String(length=64), nullable=False, comment='任务编号；TODO(待确认)'),
    sa.Column('trigger_type', sa.String(length=32), nullable=False, comment='触发方式；P0 仅 manual；TODO(待确认)'),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'partial_success', 'failed', name='collection_task_status'), nullable=False, comment='pending/running/success/partial_success/failed；TODO(待确认)：正式枚举落库'),
    sa.Column('scope_type', sa.String(length=64), nullable=False, comment='采集范围类型；TODO(待确认)'),
    sa.Column('scope_config', sa.JSON(), nullable=False, comment='账号集合、来源和范围配置；TODO(待确认)'),
    sa.Column('time_window_start', sa.DateTime(), nullable=False, comment='采集时间窗开始；TODO(待确认)：时间窗映射'),
    sa.Column('time_window_end', sa.DateTime(), nullable=False, comment='采集时间窗结束；TODO(待确认)：时间窗映射'),
    sa.Column('requested_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='发起人；TODO(待确认)'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='实际开始时间；TODO(待确认)'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='实际结束时间；TODO(待确认)'),
    sa.Column('total_count', sa.Integer(), nullable=False, comment='记录总数；TODO(待确认)'),
    sa.Column('success_count', sa.Integer(), nullable=False, comment='成功记录数；TODO(待确认)'),
    sa.Column('failure_count', sa.Integer(), nullable=False, comment='失败记录数；TODO(待确认)'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='任务级重试次数；TODO(待确认)'),
    sa.Column('error_message', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True, comment='任务级错误；TODO(待确认)'),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True, comment='同账号/时间窗/范围幂等键；TODO(待确认)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_no')
    )
    with op.batch_alter_table('collection_task', schema=None) as batch_op:
        batch_op.create_index('idx_collection_task_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_collection_task_idempotency_key', ['idempotency_key'], unique=False)
        batch_op.create_index('idx_collection_task_status', ['status'], unique=False)

    op.create_table('research_task',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('task_no', sa.String(length=64), nullable=False, comment='研究任务编号；TODO(待确认)'),
    sa.Column('topic', sa.String(length=500), nullable=False, comment='研究主题；TODO(待确认)'),
    sa.Column('objective', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False, comment='研究目标/问题；TODO(待确认)'),
    sa.Column('scope_config', sa.JSON(), nullable=False, comment='外部检索、资料和采集结果范围；TODO(待确认)'),
    sa.Column('time_window_start', sa.DateTime(), nullable=True, comment='研究时间窗开始；TODO(待确认)'),
    sa.Column('time_window_end', sa.DateTime(), nullable=True, comment='研究时间窗结束；TODO(待确认)'),
    sa.Column('status', sa.Enum('pending', 'searching', 'organizing', 'success', 'failed', name='research_task_status'), nullable=False, comment='pending/searching/organizing/success/failed；TODO(待确认)：正式枚举落库'),
    sa.Column('current_stage', sa.String(length=32), nullable=True, comment='阶段信息；TODO(待确认)：可由执行中+阶段字段替代'),
    sa.Column('progress_percent', sa.Numeric(precision=5, scale=2), nullable=True, comment='阶段进度百分比；TODO(待确认)'),
    sa.Column('progress_message', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True, comment='最近进度说明；TODO(待确认)'),
    sa.Column('checkpoint_data', sa.JSON(), nullable=True, comment='可恢复游标和中间上下文；TODO(待确认)'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='任务重试次数；TODO(待确认)'),
    sa.Column('last_error_code', sa.String(length=64), nullable=True, comment='最近错误码；TODO(待确认)'),
    sa.Column('last_error_message', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True, comment='最近错误说明；TODO(待确认)'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='开始时间；TODO(待确认)'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='完成时间；TODO(待确认)'),
    sa.Column('requested_by', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='创建人；TODO(待确认)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='修改时间'),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_no')
    )
    with op.batch_alter_table('research_task', schema=None) as batch_op:
        batch_op.create_index('idx_research_task_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_research_task_status', ['status'], unique=False)

    op.create_table('collection_record',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('task_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='关联采集任务；TODO(待确认)'),
    sa.Column('benchmark_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='关联对标账号；TODO(待确认)'),
    sa.Column('source_type', sa.String(length=64), nullable=False, comment='来源类型；TODO(待确认)：不得与资料 source_type 混用'),
    sa.Column('source_url', sa.String(length=1000), nullable=True, comment='来源 URL；TODO(待确认)'),
    sa.Column('status', sa.Enum('pending', 'running', 'success', 'failed', name='collection_record_status'), nullable=False, comment='pending/running/success/failed；TODO(待确认)'),
    sa.Column('attempt_no', sa.Integer(), nullable=False, comment='当前尝试序号；TODO(待确认)'),
    sa.Column('requested_at', sa.DateTime(), nullable=False, comment='请求时间；TODO(待确认)'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='完成时间；TODO(待确认)'),
    sa.Column('raw_response', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True, comment='来源原始响应；TODO(待确认)：json/text 存储方式'),
    sa.Column('http_status', sa.Integer(), nullable=True, comment='来源响应状态；TODO(待确认)'),
    sa.Column('item_count', sa.Integer(), nullable=False, comment='本次得到的条目数；TODO(待确认)'),
    sa.Column('error_code', sa.String(length=64), nullable=True, comment='结构化错误码；TODO(待确认)'),
    sa.Column('error_message', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True, comment='记录级错误原因；TODO(待确认)'),
    sa.Column('retryable', sa.Boolean(), nullable=False, comment='是否允许重试；TODO(待确认)'),
    sa.ForeignKeyConstraint(['benchmark_account_id'], ['benchmark_account.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['collection_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_record', schema=None) as batch_op:
        batch_op.create_index('idx_collection_record_task_status', ['task_id', 'status'], unique=False)

    op.create_table('research_report',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('research_task_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='关联研究任务；TODO(待确认)'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='报告标题；TODO(待确认)'),
    sa.Column('summary', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False, comment='报告摘要；TODO(待确认)'),
    sa.Column('content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False, comment='报告正文；TODO(待确认)'),
    sa.Column('sections', sa.JSON(), nullable=True, comment='章节、章节结论和排序；TODO(待确认)'),
    sa.Column('conclusions', sa.JSON(), nullable=True, comment='结构化结论集合；TODO(待确认)'),
    sa.Column('generation_trace', sa.JSON(), nullable=True, comment='输入快照、提示词/模型版本和生成时间；TODO(待确认)'),
    sa.Column('raw_ai_response', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True, comment='AI 原始响应；复用一期语义；TODO(待确认)'),
    sa.Column('is_ai_product', sa.Boolean(), server_default='1', nullable=False, comment='是否 AI 产物；研究报告必须 true'),
    sa.Column('status', sa.Enum('success', 'failed', 'discarded', name='research_report_status'), nullable=False, comment='success/failed/discarded；TODO(待确认)：报告状态枚举'),
    sa.Column('source_count', sa.Integer(), nullable=False, comment='关联引用数量；TODO(待确认)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='修改时间'),
    sa.CheckConstraint('is_ai_product = 1', name='ck_research_report_ai_product'),
    sa.ForeignKeyConstraint(['research_task_id'], ['research_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_task_id')
    )
    with op.batch_alter_table('research_report', schema=None) as batch_op:
        batch_op.create_index('idx_research_report_task', ['research_task_id'], unique=False)

    op.create_table('collection_result',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('record_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='关联采集记录；TODO(待确认)'),
    sa.Column('task_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='关联采集任务；TODO(待确认)'),
    sa.Column('benchmark_account_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='关联对标账号；TODO(待确认)'),
    sa.Column('business_object', sa.String(length=64), nullable=False, comment='业务对象；复用 context/05 语义'),
    sa.Column('platform', sa.String(length=32), nullable=True, comment='平台；复用 context/05 语义；TODO(待确认)：具体值'),
    sa.Column('account_identifier', sa.String(length=255), nullable=True, comment='账号标识；复用 context/05 语义'),
    sa.Column('is_benchmark', sa.Boolean(), nullable=False, comment='对标标记；复用 context/05 语义'),
    sa.Column('source_url', sa.String(length=1000), nullable=True, comment='来源链接；复用 context/05 语义；TODO(待确认)'),
    sa.Column('raw_content', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=False, comment='原始数据内容；复用 context/05 语义；TODO(待确认)：json/text 存储方式'),
    sa.Column('structured_data', sa.JSON(), nullable=True, comment='结构化数据；复用 context/05 语义；TODO(待确认)'),
    sa.Column('collected_at', sa.DateTime(), nullable=False, comment='原始数据获取时间；复用 context/05 语义'),
    sa.Column('window_start', sa.DateTime(), nullable=False, comment='采集任务时间窗开始；复用 context/05 语义'),
    sa.Column('window_end', sa.DateTime(), nullable=False, comment='采集任务时间窗结束；复用 context/05 语义'),
    sa.Column('data_cleaning_note', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True, comment='数据清洗/去重记录；复用 context/05 语义；TODO(待确认)：json/text 存储方式'),
    sa.Column('is_ai_product', sa.Boolean(), nullable=False, comment='是否 AI 产物；采集结果默认 false'),
    sa.Column('ai_derivative_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='AI 摘要/分类衍生结果关联；TODO(待确认)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['benchmark_account_id'], ['benchmark_account.id'], ),
    sa.ForeignKeyConstraint(['record_id'], ['collection_record.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['collection_task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collection_result', schema=None) as batch_op:
        batch_op.create_index('idx_collection_result_task', ['task_id'], unique=False)

    op.create_table('research_reference',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('report_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False, comment='关联研究报告；TODO(待确认)'),
    sa.Column('source_kind', sa.String(length=32), nullable=False, comment='external_url/collection_result/material；TODO(待确认)：枚举'),
    sa.Column('source_url', sa.String(length=1000), nullable=True, comment='外部来源 URL；TODO(待确认)'),
    sa.Column('source_title', sa.String(length=500), nullable=True, comment='来源标题；TODO(待确认)'),
    sa.Column('search_provider', sa.String(length=128), nullable=True, comment='检索源/供应商；TODO(待确认)，不代表锁定供应商'),
    sa.Column('collection_result_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='第二步采集结果；TODO(待确认)'),
    sa.Column('material_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True, comment='一期资料条目；TODO(待确认)'),
    sa.Column('source_snapshot', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True, comment='引用时标题/摘要/原文快照；TODO(待确认)：json/text 存储方式'),
    sa.Column('page_number', sa.String(length=64), nullable=True, comment='页码；引用增强字段；TODO(待确认)'),
    sa.Column('paragraph_locator', sa.String(length=255), nullable=True, comment='段落/章节定位；引用增强字段；TODO(待确认)'),
    sa.Column('evidence_summary', sa.Text().with_variant(mysql.LONGTEXT(), 'mysql'), nullable=True, comment='证据摘要；引用增强字段；TODO(待确认)'),
    sa.Column('source_type', sa.String(length=64), nullable=True, comment='检索源类型；引用增强字段；TODO(待确认)'),
    sa.Column('cited_at', sa.DateTime(), nullable=False, comment='建立引用时间；TODO(待确认)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.ForeignKeyConstraint(['collection_result_id'], ['collection_result.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['research_report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_reference', schema=None) as batch_op:
        batch_op.create_index('idx_research_reference_report', ['report_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_reference', schema=None) as batch_op:
        batch_op.drop_index('idx_research_reference_report')

    op.drop_table('research_reference')
    with op.batch_alter_table('collection_result', schema=None) as batch_op:
        batch_op.drop_index('idx_collection_result_task')

    op.drop_table('collection_result')
    with op.batch_alter_table('research_report', schema=None) as batch_op:
        batch_op.drop_index('idx_research_report_task')

    op.drop_table('research_report')
    with op.batch_alter_table('collection_record', schema=None) as batch_op:
        batch_op.drop_index('idx_collection_record_task_status')

    op.drop_table('collection_record')
    with op.batch_alter_table('research_task', schema=None) as batch_op:
        batch_op.drop_index('idx_research_task_status')
        batch_op.drop_index('idx_research_task_created_at')

    op.drop_table('research_task')
    with op.batch_alter_table('collection_task', schema=None) as batch_op:
        batch_op.drop_index('idx_collection_task_status')
        batch_op.drop_index('idx_collection_task_idempotency_key')
        batch_op.drop_index('idx_collection_task_created_at')

    op.drop_table('collection_task')
    with op.batch_alter_table('benchmark_account', schema=None) as batch_op:
        batch_op.drop_index('idx_benchmark_account_platform')
        batch_op.drop_index('idx_benchmark_account_enabled')

    op.drop_table('benchmark_account')
    # ### end Alembic commands ###
